/*
=========================================
    LOAD state_dim
=========================================
*/

INSERT INTO state_dim (state, state_abbr, country_code) VALUES
-- US
('Alabama', 'AL', 'US'),
('Alaska', 'AK', 'US'),
('American Samoa', 'AS', 'US'),
('Arizona', 'AZ', 'US'),
('Arkansas', 'AR', 'US'),
('California', 'CA', 'US'),
('Colorado', 'CO', 'US'),
('Connecticut', 'CT', 'US'),
('Delaware', 'DE', 'US'),
('District of Columbia', 'DC', 'US'),
('Florida', 'FL', 'US'),
('Georgia', 'GA', 'US'),
('Guam', 'GU', 'US'),
('Hawaii', 'HI', 'US'),
('Idaho', 'ID', 'US'),
('Illinois', 'IL', 'US'),
('Indiana', 'IN', 'US'),
('Iowa', 'IA', 'US'),
('Kansas', 'KS', 'US'),
('Kentucky', 'KY', 'US'),
('Louisiana', 'LA', 'US'),
('Maine', 'ME', 'US'),
('Maryland', 'MD', 'US'),
('Massachusetts', 'MA', 'US'),
('Michigan', 'MI', 'US'),
('Minnesota', 'MN', 'US'),
('Mississippi', 'MS', 'US'),
('Missouri', 'MO', 'US'),
('Montana', 'MT', 'US'),
('Nebraska', 'NE', 'US'),
('Nevada', 'NV', 'US'),
('New Hampshire', 'NH', 'US'),
('New Jersey', 'NJ', 'US'),
('New Mexico', 'NM', 'US'),
('New York', 'NY', 'US'),
('North Carolina', 'NC', 'US'),
('North Dakota', 'ND', 'US'),
('Northern Mariana Islands', 'MP', 'US'),
('Ohio', 'OH', 'US'),
('Oklahoma', 'OK', 'US'),
('Oregon', 'OR', 'US'),
('Pennsylvania', 'PA', 'US'),
('Puerto Rico', 'PR', 'US'),
('Rhode Island', 'RI', 'US'),
('South Carolina', 'SC', 'US'),
('South Dakota', 'SD', 'US'),
('Tennessee', 'TN', 'US'),
('Texas', 'TX', 'US'),
('Trust Territories', 'TT', 'US'),
('Utah', 'UT', 'US'),
('Vermont', 'VT', 'US'),
('Virgin Islands', 'VI', 'US'),
('Virginia', 'VA', 'US'),
('Washington', 'WA', 'US'),
('West Virginia', 'WV', 'US'),
('Wisconsin', 'WI', 'US'),
('Wyoming', 'WY', 'US'),
-- Canada
('Alberta', 'AB', 'CA'),
('British Columbia', 'BC', 'CA'),
('Manitoba', 'MB', 'CA'),
('New Brunswick', 'NB', 'CA'),
('Newfoundland and Labrador', 'NL', 'CA'),
('Northwest Territories', 'NT', 'CA'),
('Nova Scotia', 'NS', 'CA'),
('Nunavut', 'NU', 'CA'),
('Ontario', 'ON', 'CA'),
('Prince Edward Island', 'PE', 'CA'),
('Quebec', 'QC', 'CA'),
('Saskatchewan', 'SK', 'CA'),
('Yukon', 'YT', 'CA');